-- [TEST MOCK] E2E-09 문자발송 뒤 정리. 발송 실패 시에도 SSG_TRAN 행이 남는다(LmsDispatchSO catch 로 롤백 안 됨 — 결함).
DELETE FROM SSG_TRAN WHERE TRAN_MESSAGE LIKE 'TEST_E2E09%';
DELETE FROM SSG_CLIENT WHERE TRAN_NO NOT IN (SELECT TRAN_NO FROM SSG_TRAN);
DELETE FROM TBS_VOC_EMAIL_FILTER WHERE TOEMAIL LIKE 'TEST_E2E09%';
SELECT (SELECT COUNT(*) FROM SSG_TRAN) TRAN, (SELECT COUNT(*) FROM SSG_CLIENT) CLIENT, (SELECT COUNT(*) FROM TBS_VOC_EMAIL_FILTER WHERE TOEMAIL LIKE 'TEST_E2E09%') MAIL;
