-- [TEST MOCK] E2E-02 목업 원복 (2026-08-27 검증본) — 실행 후 SELECT 가 전부 0 이어야 함
DELETE FROM TBS_STORECARE WHERE ID_REG_EMP='TEST_E2E02';
DELETE FROM TBS_STORECARE_CAUSE WHERE ID_REG_EMP='TEST_E2E02';
DELETE FROM TBS_STORE WHERE CD_STORE='9024' AND ID_REG_EMP='TEST_E2E02';
DROP TABLE IF EXISTS STB_MEMBER;
SELECT (SELECT COUNT(*) FROM TBS_STORECARE WHERE ID_REG_EMP='TEST_E2E02') SC,
       (SELECT COUNT(*) FROM TBS_STORECARE_CAUSE WHERE ID_REG_EMP='TEST_E2E02') SCC,
       (SELECT COUNT(*) FROM TBS_STORE WHERE CD_STORE='9024') ST;
