-- [TEST MOCK] E2E-04 목업 원복
DELETE FROM TBS_CE_ANSWER WHERE ID_ISSUE LIKE 'TEST04%';
DELETE FROM TBS_CE_YM_STDN WHERE YM_STDN='202608' AND ID_REG_EMP='TEST_E2E04';
SELECT (SELECT COUNT(*) FROM TBS_CE_ANSWER WHERE ID_ISSUE LIKE 'TEST04%') CE, (SELECT COUNT(*) FROM TBS_CE_YM_STDN WHERE ID_REG_EMP='TEST_E2E04') CEYM;
